name: Run Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zsh \
            gcc \
            g++ \
            openjdk-11-jdk \
            rustc \
            nodejs \
            npm \
            php \
            ruby \
            perl \
            lua5.3


      - name: Make scripts executable
        run: chmod +x ./*.zsh

      - name: Run test suite
        run: ./test_runner.zsh